<script type="text/javascript" src="{{ asset('assets/web/js/popper.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/web/js/slick.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/web/js/carousel.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/web/js/appjs.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/web/js/script.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/web/js/bootstrap.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/web/js/summernote.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/web/js/datatables.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/dev_custom.js') }}"></script>
